import os
print("                   Welcome to the SSH-OS installer                ")
print("                                                                  ")
print("          -+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-           ")
print("                                                                  ")
os.system('sudo apt-get install openssh-server')
os.system('sudo service ssh start')
os.chdir('/etc/')
os.system('sudo rm motd')
os.system('sudo rm banner')
os.chdir('/etc/ssh/')
os.system('sudo rm ssh_config')
os.system('sudo rm sshd_config') 
os.system('sudo git clone http://github.com/PizzaRollProgramma/SSH-OS')
os.chdir('/etc/ssh/SSH-OS/')
os.system('sudo mv ssh_config ..')
os.system('sudo mv sshd_config ..')
os.system('sudo mv banner ../../')
os.system('sudo mv motd ../../')
os.system('g++ Electron-OS.cpp -o Electron-OS')
os.system('sudo mv Electron-OS ../../../root/')
os.system('sudo service ssh restart')
print("Install Complete")
print("Now try to ssh, if it doesn't work reboot")
d = input("")
